name: Commit Diario

on:
  schedule:
    - cron: '15 3 * * *'  # 03:15 UTC
    - cron: '42 8 * * *'  # 08:42 UTC
    - cron: '7 13 * * *'  # 13:07 UTC
    - cron: '51 17 * * *' # 17:51 UTC
    - cron: '28 22 * * *' # 22:28 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configurar Git
        run: |
          git config --global user.name 'mariops03'
          git config --global user.email 'marioprieta@gmail.com'
      - name: Checkout del repositorio
        uses: actions/checkout@v2
      - name: Otorgar permisos de ejecución al script
        run: chmod +x ./.github/scripts/auto_commit.sh
      - name: Ejecutar script de auto-commit
        run: ./.github/scripts/auto_commit.sh
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}